apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: mej3n0czo-nodejs 
  janus-idp.io/tekton: mej3n0czo-nodejs
  backstage.io/kubernetes-id: mej3n0czo-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: mej3n0czo-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  