apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: mej3n0czo-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: mej3n0czo-nodejs 
  name: mej3n0czo-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: mej3n0czo-nodejs 
